#!/usr/bin/env python3
"""Export Figure 12's curve and bands to pgfplots tables.

Imports FC_KIE from marcus_rate_A_v3.py so the curve is the same analytic model, not a
reimplementation. The five snapshot r_DA values come from results/pcet_B34_dense/*_scan.json.

PROVENANCE NOTE. Those files sit in a directory whose QM PROTON SCANS are invalidated
(5-point / M=5 / charge +2). Only the field r_DA is read here, which is a geometric property
of the snapshot and is unaffected by the SCF settings used to scan a proton on it.
"""
import os as _os
_REPO = _os.environ.get('PAULI_ROOT') or _os.path.abspath(
    _os.path.join(_os.path.dirname(_os.path.abspath(__file__)), '..'))

import importlib.util, json
from pathlib import Path
import numpy as np

ROOT = Path(_REPO)
spec = importlib.util.spec_from_file_location('m3', ROOT / 'scripts/marcus_rate_A_v3.py')
m = importlib.util.module_from_spec(spec)
spec.loader.exec_module(m) if False else None
# exec only the definitions we need, without running its main/plot block
src = (ROOT / 'scripts/marcus_rate_A_v3.py').read_text()
ns = {}
exec(src[:src.index('def main')] if 'def main' in src else src.split('    # Plot')[0], ns)

FC = ns['FC_KIE']
g = json.loads((ROOT / 'results/pcet_B34_dense/marcus_rate_A_v3.json').read_text())

r = np.linspace(2.40, 4.00, 400)
with (ROOT / 'figures/figED3_curve.dat').open('w') as f:
    f.write('# Figure 12: Franck-Condon KIE from harmonic wells, k = 500 N/m.\n')
    f.write('# Curve from FC_KIE() of scripts/marcus_rate_A_v3.py.\n')
    f.write('r\tkie\n')
    for x in r:
        v = FC(float(x))
        k = v['KIE_HD']
        f.write(f'{x:.4f}\t{k:.6e}\n')

snap = []
for w in ['270', '320', '345', '370', '395']:
    snap.append(json.loads((ROOT / f'results/pcet_B34_dense/wt_win{w}_scan.json').read_text())['r_DA'])
snap = np.array(snap)

with (ROOT / 'figures/figED3_meta.tex').open('w') as f:
    f.write('% Generated by scripts/export_figED3_data.py. Do not edit.\n')
    f.write(f'\\def\\gSnapLo{{{snap.min():.3f}}}\\def\\gSnapHi{{{snap.max():.3f}}}\n')
    f.write(f'\\def\\gSnapMean{{{snap.mean():.2f}}}\n')
    f.write(f'\\def\\gRLo{{{g["r_reactive_KIE66"]:.2f}}}\\def\\gRHi{{{g["r_reactive_KIE148"]:.2f}}}\n')
print(f'  five snapshot r_DA: {np.round(snap,3)}')
print(f'  range {snap.min():.3f} to {snap.max():.3f}, mean {snap.mean():.3f}')
print(f'  reactive r_DA {g["r_reactive_KIE66"]:.3f} to {g["r_reactive_KIE148"]:.3f}')
print(f'  KIE at the snapshot mean: {FC(float(snap.mean()))["KIE_HD"]:.3e}')
