#!/usr/bin/env python3
"""Export Figure 8 (figED1) to pgfplots tables so the TikZ carries no numbers.

One table of the five computed points per system, one of the fitted quadratics sampled
finely, and one rank table. Values come from the native-fragment campaign results and the
parametric-bootstrap uncertainties, the same files the manuscript table quotes.
"""
import json
from pathlib import Path
import numpy as np

ROOT = Path('/home/liang/Workspace/WritePaper/CatalysisQuamBio')
NF = ROOT / 'results/sapt_bio/native_fragment'
U = json.loads((ROOT / 'results/sapt_bio/native_fragment_uncertainty.json').read_text())['systems']
KIE = {'WT': 66, 'V750A': 62, 'I552A': 66, 'I538A': 100,
       'L754A': 106, 'L546A': 131, 'I553A': 148}

rows = []
for t, u in sorted(U.items(), key=lambda kv: kv[1]['k_exch_Nm']):
    d = json.loads((NF / f'{t}_native_result.json').read_text())
    # deltas maps the displacement (as a string) to the SAPT components; we plot exch
    dl = d['deltas']
    keys = sorted(dl, key=float)
    xs = [float(k) for k in keys]
    ys = [dl[k]['exch'] for k in keys]
    rows.append((t, u, xs, ys))

with (ROOT / 'figures/figED1_points.dat').open('w') as f:
    f.write('# Figure 8 (figED1): five computed SAPT0 points per system.\n')
    f.write('# From results/sapt_bio/native_fragment/*_native_result.json.\n')
    f.write('system\tdelta\tE\n')
    for t, u, xs, ys in rows:
        for x, y in zip(xs, ys):
            f.write(f'{t}\t{x:.3f}\t{y:.8f}\n')
        f.write('\n')

with (ROOT / 'figures/figED1_rank.dat').open('w') as f:
    f.write('# Figure 8 rank panel: fitted curvature by system, ascending.\n')
    f.write('i\tsystem\tk\tsigma\tkie\trHW\trms\twall\n')
    for i, (t, u, _, _) in enumerate(rows):
        f.write(f"{i}\t{t}\t{u['k_exch_Nm']:.6f}\t{u['sigma_k_Nm']:.6f}\t{KIE[t]}\t"
                f"{u['r_HW_A']:.3f}\t{u['RMS_residual_kcal']:.6f}\t{u['wall_residue']}\n")

# fitted quadratics, sampled finely, so the TikZ draws the curve without refitting
with (ROOT / 'figures/figED1_curves.dat').open('w') as f:
    f.write('# Figure 8: least-squares quadratic through the five points, sampled.\n')
    f.write('system\tdelta\tE\n')
    for t, u, xs, ys in rows:
        c = np.polyfit(xs, ys, 2)
        for x in np.linspace(min(xs), max(xs), 60):
            f.write(f'{t}\t{x:.4f}\t{np.polyval(c, x):.8f}\n')
        f.write('\n')

# per-panel annotation strings, GENERATED so no value is hand-typed into the TikZ
with (ROOT / 'figures/figED1_labels.tex').open('w') as f:
    f.write('% Generated by scripts/export_figED1_data.py. Do not edit.\n')
    for t, u, xs, ys in rows:
        k, sg = u['k_exch_Nm'], u['sigma_k_Nm']
        kk = f'{k:.4f}' if k < 0.01 else f'{k:.2f}'
        ss = f'{sg:.4f}' if sg < 0.01 else f'{sg:.2f}'
        f.write(f'\\expandafter\\def\\csname edA{t}\\endcsname{{$k={kk}\\pm{ss}$}}\n')
        f.write(f'\\expandafter\\def\\csname edB{t}\\endcsname'
                f'{{$r_{{\\mathrm{{HW}}}}={u["r_HW_A"]:.2f}$\\,\\AA}}\n')
        f.write(f'\\expandafter\\def\\csname edC{t}\\endcsname'
                f'{{rms {u["RMS_residual_kcal"]:.3f}}}\n')
        f.write(f'\\expandafter\\def\\csname edK{t}\\endcsname{{{KIE[t]}}}\n')

print(f'wrote figED1_points.dat, figED1_curves.dat, figED1_rank.dat, figED1_labels.tex '
      f'for {len(rows)} systems')
for t, u, xs, ys in rows:
    print(f'  {t:6s} k={u["k_exch_Nm"]:8.4f} +/- {u["sigma_k_Nm"]:.4f}  '
          f'{len(xs)} points at delta {min(xs):+.2f}..{max(xs):+.2f}')
