#!/usr/bin/env python3
"""Export Figure 10's four bead-density histograms to a pgfplots matrix table.

Imports the projection and binning from render_fig6.py rather than reimplementing them, so the
grids are the same numbers the superseded matplotlib figure drew. Emits one table per condition
plus the shared colour-scale maximum and the annotated entropies.
"""
import importlib.util, sys
from pathlib import Path
import numpy as np

ROOT = Path('/home/liang/Workspace/WritePaper/CatalysisQuamBio')
spec = importlib.util.spec_from_file_location('rf6', ROOT / 'scripts/render_fig6.py')
m = importlib.util.module_from_spec(spec)
m.__dict__['__name__'] = 'rf6'
import matplotlib
matplotlib.use('Agg')
spec.loader.exec_module(m)           # computes data, hists, S, N_eff, max_prob

conds = [('I553A', 'H'), ('I553A', 'D'), ('I552A', 'H'), ('I552A', 'D')]
for s, i in conds:
    H, xe, ye, _ = m.hists[(s, i)]
    p = H / (H.sum() + 1e-30)
    with (ROOT / f'figures/fig6_{s}_{i}.dat').open('w') as f:
        f.write(f'# Figure 10 density, {s} {i}. From scripts/export_fig6_data.py, which imports\n')
        f.write(f'# the projection and binning of render_fig6.py. probability per bin.\n')
        f.write('x\ty\tp\n')
        for a in range(len(xe) - 1):
            for b in range(len(ye) - 1):
                f.write(f'{0.5*(xe[a]+xe[a+1]):.5f}\t{0.5*(ye[b]+ye[b+1]):.5f}\t{p[a,b]:.8e}\n')
            f.write('\n')

with (ROOT / 'figures/fig6_meta.tex').open('w') as f:
    f.write('% Generated by scripts/export_fig6_data.py. Do not edit.\n')
    f.write(f'\\def\\fsixmax{{{m.max_prob:.6f}}}\n')
    f.write(f'\\def\\fsixrlo{{{m.r_range[0]:.3f}}}\\def\\fsixrhi{{{m.r_range[1]:.3f}}}\n')
    f.write(f'\\def\\fsixtlo{{{m.t_range[0]:.2f}}}\\def\\fsixthi{{{m.t_range[1]:.2f}}}\n')
    for s, i in conds:
        f.write(f'\\expandafter\\def\\csname fsixN{s}{i}\\endcsname'
                f'{{{m.N_eff[(s,i)]:.1f}}}\n')
    for s in ('I553A', 'I552A'):
        r = np.log(m.N_eff[(s,'H')] / m.N_eff[(s,'D')])
        f.write(f'\\expandafter\\def\\csname fsixR{s}\\endcsname{{{r:+.3f}}}\n')

print(f'wrote 4 density tables ({m.NB}x{m.NB} bins) and fig6_meta.tex')
print(f'  colour max {m.max_prob:.5f}   r range {m.r_range[0]:.3f}-{m.r_range[1]:.3f} A'
      f'   theta {m.t_range[0]:.1f}-{m.t_range[1]:.1f} deg')
for s, i in conds:
    print(f'  {s} {i}: N~ = {m.N_eff[(s,i)]:.1f}')
for s in ('I553A', 'I552A'):
    print(f'  {s}: ln(N_H/N_D) = {np.log(m.N_eff[(s,"H")]/m.N_eff[(s,"D")]):+.4f}')
